default_platform(:android)

platform :android do
  desc "TestFairy debug upload"
  lane :testfairy_debug do
    increment_version_code
    commit_android_version_bump(
      force:true
    )
    push_to_git_remote(
      local_branch: "main"
    )
    gradle(
      task: 'clean assemble',
      build_type: 'debug'
    )
    testfairy(
      api_key: ENV["TESTFAIRY_API_KEY"],
      testers_groups: "all"
    )
  end
end
