name: Android CI

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main

jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: set up JDK 11
#       uses: actions/setup-java@v2
#       with:
#         java-version: '11'
#         distribution: 'adopt'
#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew
#     - name: Build with Gradle
#       run: ./gradlew assembleDebug

#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     # Setting up ruby on the machine
#     - name: Set up Ruby
#       id: set_up_ruby
#       uses: actions/setup-ruby@v1
#       with:
#         ruby-version: '2.7'
#     # Installing firebase on the machine
#     - name: Install firebase tool
#       id: install_firebase_tool
#       run: |
#         yarn global add firebase-tools
#         echo "::add-path::$(yarn global bin)"
#     # Installing bundler to use fastlane on the machine
#     - name: Setup fastlane
#       id: set_up_fastlane
#       run: |
#         gem install bundler:1.17.2
#         bundle config path vendor/bundle
#         bundle install --jobs 4 --retry 3
#     # run fastlane
#     - name: Run fastlane for testfairy
#       id: run_fastlane_testfairy
#       run: |
#         bundle exec fastlane run testfairy api_key:"${{ secrets.TESTFAIRY_API_KEY }}"

    deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'testfairy'
          options: '{ "api_key": "${{ secrets.TESTFAIRY_API_KEY }}" }'
